config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations'
  }

  root 'home#index'

  resources :cars

  resources :message_threads, only: [:index, :new, :show, :create]

  resources :messages, only: [:create]

end

app/models/message_thread.rb
# == Schema Information
#
# Table name: message_threads
#
#  id                :integer          not null, primary key
#  started_user_id   :integer
#  to_user_id        :integer
#  latest_message_id :integer
#  subject           :string
#  is_deleted        :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class MessageThread < ActiveRecord::Base
  belongs_to :started_user, class_name: User
  belongs_to :to_user, class_name: User
  belongs_to :latest_message, :class_name => "Message", :foreign_key => "latest_message_id"

  has_many :messages, -> {order 'created_at asc'}

  validates :subject, :presence => true
  validates :to_user_id, :presence => true
  validates :started_user_id, :presence => true

  scope :of_user, ->(user) { where("started_user_id = ? OR to_user_id = ?", user.id, user.id).order("created_at desc") }
end

app/controllers/message_threads_controller.rb
class MessageThreadsController < ApplicationController
  before_action :authenticate_user!

  def index
    @message_threads = MessageThread.of_user(current_user)
  end

  # Find all messages related to given message thread
  # Mark messages of given thread related to current user as read
  def show
    @message_thread = MessageThread.find(params[:id])
    @message_thread.messages.each do |message|
      if message.sender.equal_user?(current_user)
        message.update(is_sender_read: true)
      else
        message.update(is_receiver_read: true)
      end
    end
    @message = Message.new
  end

  # In case users send message to themselves or to_user does not exist,
  # redirect users to 'not found' page
  def new
    if User.exists?(params[:to_user]) && current_user.id != params[:to_user] && Car.exists?(params[:car_id])
      @to_user = User.find(params[:to_user])
      @car = Car.find(params[:car_id])
      @message_thread = MessageThread.new
    else
      render_not_found
    end
  end

  # Create message thread & its first message then redirect to that message thread page
  def create
    @message_thread = MessageThread.new(message_thread_param)
    @message_thread.started_user_id = current_user.id

    if @message_thread.save
      message = Message.new
      message.message_thread = @message_thread
      message.sender = current_user
      message.is_sender_read = true
      message.is_receiver_read = false
      message.receiver = @message_thread.to_user
      message.body = params[:message]

      if message.save
        @message_thread.update(latest_message_id: message.id)
        flash[:success] = "Message has been sent!"
        redirect_to @message_thread
      end
    end
  end

  private
    def message_thread_param
      params.require(:message_thread).permit(:to_user_id, :subject)
    end
end

app/helpers/message_threads_helper.rb
module MessageThreadsHelper
end

app/views/message_threads/index.html.slim
.row
  section.content
    h1 = 'Inbox (' + @total_unread_messages.to_s + ')'
    .row
      .col-md-12
        .panel.panel-default
          .panel-body
            .table-container
              - if !@message_threads.empty?
                table.table.table-filter
                  tbody
                    - @message_threads.each do |thread|
                      tr.message-thread-row data-id=thread.id onclick="window.location='#{message_thread_path(thread)}'"
                        td
                          .media
                            .media-left
                              = link_to image_tag(thread.started_user.avatar.url(:thumb), :class => 'media-photo'), cars_path(:user_id => thread.started_user.id)  , class: 'pull-left'
                            .media-body
                              h4.title = thread.subject
                              p.summary = thread.latest_message.body.split[0...10].join(' ') << "..."
                              span.media-meta.pull-right = thread.created_at.strftime("%d-%m-%Y %H:%M:%S")
                              span.pull-right.pagado = thread.started_user.full_name
              - if @message_threads.empty?
                p No messages

app/views/message_threads/new.html.slim
= render "cars/detail"
.row
  .col-md-12
    h2 = 'Send message to ' << @to_user.full_name << ' to rent this car'
    = form_for @message_thread do |f|
      = f.hidden_field :to_user_id, :value => @to_user.id
      .form-group
        = f.label :subject
        = f.text_field :subject, class: 'form-control'
      .form-group
        = f.label 'Content'
        = text_area_tag :message, nil, rows: 4, cols: 100, class: 'form-control'
      .form-group
        = f.submit 'Send', class: 'btn btn-primary'

app/views/message_threads/show.html.slim
.row
  .col-md-12
    h1 = @message_thread.subject
    p
      | Exchange messages with
      - user = @message_thread.started_user.equal_user?(current_user) ? @message_thread.to_user : @message_thread.started_user
      = link_to " " + user.full_name, cars_path(:user_id => user.id)
    ul.media-list
      - @message_thread.messages.each do |message|
        li.media
          .media-body
            .media
              = link_to image_tag(message.sender.avatar.url(:thumb), :class => 'media-photo'), cars_path(:user_id => message.sender.id), class: 'pull-left'
              .media-body = message.body
              br
              br
              small.text-muted = "#{message.sender.full_name} | #{message.created_at.strftime("%d-%m-%Y %H:%M:%S")}"
              hr
  .col-md-12
    h1 = 'Reply '
    = form_for @message do |f|
      = f.hidden_field :message_thread_id, :value => @message_thread.id
      .form-group
        = f.label 'Message'
        = f.text_area :body, rows: 4, cols: 100, class: 'form-control'
      .form-group
        = f.submit 'Send', class: 'btn btn-primary'