config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations'
  }

  root 'home#index'

  resources :cars

  resources :message_threads, only: [:index, :new, :show, :create]

  resources :messages, only: [:create]

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id                 :integer          not null, primary key
#  brand              :string
#  model              :string
#  seat               :integer
#  color              :string
#  price              :integer
#  public_year        :integer
#  description        :text
#  user_id            :integer
#  activate           :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Car < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://www.ecijagamingcommunity.com/wp-content/themes/cwp-youit/images/no-image-default.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :brand, presence: true, length: { minimum: 3 }
	validates :model, presence: true, length: { minimum: 2 }

	scope :latest_cars, -> { limit(4).order('created_at DESC') }
	scope :of_user, ->(user) { where('user_id = ?', user.id).order('created_at DESC') }
	
	# Get all car activated
	scope :get_cars, -> { order('created_at DESC') }

	# Search Car base on Brand, Model or Description
	def self.search(search)
	  where("brand LIKE ? OR model LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :create]

  # GET /cars
  # Show search result or list all cars
  def index
    if params[:search]
      @cars = Car.search(params[:search]).order("created_at DESC")
    elsif params[:user_id]
      @user = User.find(params[:user_id])
      @cars = Car.of_user(@user)
    else
      @cars = Car.all.order("created_at DESC")
    end
  end

  # GET /cars/1
  def show
    @car = Car.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
    @public_year = ["2017","2016","2015","2014","2013","2012","2011","2010","2009","2008","2007"]
    @seat = [2,4,7,9,16,40]
    #@colors = ["green","blue","white","black","red","other"]
  end

  # GET /cars/1/edit
  def edit
    @public_year = ["2017","2016","2015","2014","2013","2012","2011","2010","2009","2008","2007"]
    @seat = [2,4,7,9,16,40]
    #@colors = ["green","blue","white","black","red","other"]
  end

  # POST /cars
  # Create new car for current user
  def create
    @car = Car.new(car_params)
    @car.user = current_user

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, success: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, success: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :seat, :color, :price, :public_year, :description, :user_id, :activate, :image)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_detail.html.slim
.row
  .col-md-12
    h1 = "#{@car.brand} #{@car.model}"
.row
  .col-md-4
    = image_tag @car.image.url(:medium), class: 'thumbnail' if @car.image?
  .col-md-8.car-detail
    p
      strong Brand:
      span = @car.brand
    p
      strong Model:
      span = @car.model
    p
      strong Seat:
      span = @car.seat
    p
      strong Color:
      span = @car.color
    p
      strong Cost:
      span = @car.price
    p
      strong Added Date:
      span = @car.created_at.strftime("%d-%m-%Y %H:%M:%S")
    p
      strong Public year:
      span = @car.public_year
    p
      strong Owner:
      span = @car.user.full_name << " (" << @car.user.email << ")"
    p
      strong Owner's city:
      span = @car.user.city
    p
      strong Owner's address:
      span = @car.user.address
    p
      strong Description:
    p = @car.description

app/views/cars/_form.html.slim
= form_for @car, :html => {:multipart => true} do |f|
  - if @car.errors.any?
    #error_explanation
      h2 = "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      ul
        - @car.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :brand
    = f.text_field :brand, autofocus: true, class: 'form-control'
  .form-group
    = f.label :model
    = f.text_field :model, autofocus: true, class: 'form-control'
  .form-group
    = f.label :seat
    = f.select :seat, @seat.map { |value| [ value, value ] }, {}, {:class => 'form-control'}
  .form-group
    = f.label :color
    = f.text_field :color, autofocus: true, class: 'form-control'
  .form-group
    = f.label :price, "Price (USD / Day)"
    = f.number_field :price, autofocus: true, class: 'form-control'
  .form-group
    = f.label :public_year
    = f.select :public_year, @public_year.map { |value| [ value, value ] }, {}, {:class => 'form-control'}
  .form-group
    = f.label :image
    = f.file_field :image, autofocus: true, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, autofocus: true, class: 'form-control'
  .form-group
    .actions = f.submit 'Submit', class: 'btn btn-primary'

app/views/cars/edit.html.slim
.panel.panel-default.devise-bs
  .panel-heading
    h1
      = t('.edit_car', default: 'Editing car')
  .panel-body
		== render 'form'

= link_to 'Show', @car
'  |
= link_to 'Back', cars_path

app/views/cars/index.html.slim
.row
  .col-md-12
    - if @user
      h1 = "Cars of " + @user.full_name
    - else
      h1 Cars
.row
  .col-md-12
    = form_tag(cars_path, :method => "get", id: "search-form") do
      .row
        .col-md-4
          = text_field_tag :search, params[:search], placeholder: "Search Cars", class: 'form-control'
        .col-md-4
          = submit_tag "Search", :class => 'btn'
        .col-md-4 = link_to 'Add your new car', new_car_path, class: 'btn btn-primary pull-right'
br
.row
  - @cars.each do |car|
    .col-md-3.col-sm-6.hero-feature
      .thumbnail.car
        = link_to car do
          = image_tag car.image.url(:medium), class: 'thumbnail'
        .caption
          h3 ="#{car.brand} #{car.model}"
          p = car.description.split[0...10].join(' ') << "..."
          p
            - if current_user && current_user.equal_user?(car.user)
              = link_to "View detail", car, class: 'btn btn-primary'
            - else
              = link_to "Send message to car owner", new_message_thread_path(:to_user => car.user_id, :car_id => car.id), class: 'btn btn-primary'

app/views/cars/new.html.slim
.panel.panel-default.devise-bs
  .panel-heading
    h4 = t('.new_car', default: 'New Car')
  .panel-body
		== render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.slim
p#notice = notice

= render "cars/detail"

.row.pull-right
  - if current_user.nil? || !current_user.equal_user?(@car.user)
    = link_to "Send a message to " << @car.user.full_name << " to rent", new_message_thread_path(:to_user => @car.user.id, :car_id => @car.id), class: 'btn btn-primary'
.row
  - if current_user.id == @car.user.id
    .col-md-12
      = link_to 'Edit', edit_car_path(@car), class: 'btn btn-primary pull-right'
      = link_to 'Destroy', @car, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-primary pull-right margin-right10'
    |
  = link_to '<< Back', cars_path