config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations'
  }

  root 'home#index'

  resources :cars

  resources :message_threads, only: [:index, :new, :show, :create]

  resources :messages, only: [:create]

end

app/views/layouts/_menu.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"  Car Rental
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          a href="/cars/"  Cars
      ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          li
            = link_to 'My account (' << current_user.email << ')', edit_user_registration_path
          li
            = link_to 'Inbox (' + @total_unread_messages.to_s + ')', message_threads_path
          li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          li
            = link_to 'Sign in', new_user_session_path
          li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    title Car Rental
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :javascripts
  body
    = render "layouts/menu"
    .container
      - if !flash[:success].nil?
        .alert.alert-success
          strong Success! 
          = flash[:success]
      = yield
      hr

      footer
        .row
          .col-lg-12
            p Copyright © EVIZI 2017